# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c757c550a578a3ce60001ba197fe63a8068915658e6567e8e61ae14c810ce62a5882548fbf6d7e9f8d2fcd7735f2c8851ea338bd21a3aec03fa20c5b10302310

test:
  secret_key_base: 39720ea22355f7db0bdc93cbc3917ff27d8443de519594c26860724803a306ea5c17732c8ad2cf60b6a12bafffff83ee570ca3622e137dde7945b6bb6ac931f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
